### ISSUE TITLE
Files unrelated to fork bombs

### ISSUE THREAD

**Issue by aaronryank** [mcandre/forkbombs#11]
I don't see how some of the files in the base directory are related to fork bombs, namely:

 - [sample.envrc](https://github.com/mcandre/forkbombs/blob/master/sample.envrc)
 - [.editorconfig](https://github.com/mcandre/forkbombs/blob/master/.editorconfig)

What are their purposes in this repository?

**Comment by mcandre** [comment]
direnv and editorconfig
